// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'button': string;
  'gradAnim': string;
  'ui': string;
  'video': string;
}
export const cssExports: CssExports;
export default cssExports;
